### ISSUE TITLE
Summary table

### ISSUE THREAD

**Issue by kmunve** [NVE/skredview#3]
Show a table with statistics of the avalanches within the chosen region and/or period.
The table can be at the bottom of the page.

Table content:

- Total number of avalanche (all)
- Total number of avalanche (<24 h precision) 
- Size (median)
- Size (mean)
- Size (min)
- Size (max)
- Aspect (median)

**Comment by widforss** [comment]
I think this might be better off on the left panel (though it could look weird on a mobile device, that's hard to test as long we're fully on the internal network).

**Comment by kmunve** [comment]
Your right. There is plenty of space on the left panel. We put it on the left panel then.
